CREATE TABLE IF NOT EXISTS registrations (
  id SERIAL PRIMARY KEY,
  type TEXT NOT NULL,
  "studentName" TEXT NOT NULL,
  dob DATE,
  age TEXT,
  sex TEXT,
  nationality TEXT,
  "schoolName" TEXT,
  "siblingsName" TEXT,
  "regNo" TEXT,
  occupation TEXT,
  area TEXT,
  "fatherName" TEXT,
  "fatherContact" TEXT,
  "fatherEmail" TEXT,
  "motherName" TEXT,
  "motherContact" TEXT,
  "motherEmail" TEXT,
  "tshirtSize" TEXT,
  "sessionsPerMonth" TEXT,
  "enrollmentDate" DATE,
  "feesPerMonth" TEXT,
  "squadLevel" TEXT,
  "studentSignature" TEXT,
  "declarationDate" DATE,
  "proofType" TEXT,
  "photoUrl" TEXT,
  "proofUrl" TEXT,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
